/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mappanel.window;


public class DebugConsole extends javax.swing.JPanel 
{

    private MapPanel map;
    
    /**
     * Creates new form DebugConsole
     */
    public DebugConsole() 
    {
        initComponents();
    }

    DebugConsole(MapPanel map)
    {
        this.map = map;
        initComponents();
    }
    
    public void tick()
    {
        if(this.isVisible())
        {
            this.mouseLonDisplayText.setText((new Double(map.getMouseLon())).toString());
            this.mouseLatDisplayText.setText((new Double(map.getMouseLat())).toString());
            this.minZoomDisplayText.setText((new Integer(map.getMinZoom())).toString());
            this.currentZoomDisplayText.setText((new Integer(map.getZoom())).toString());
            this.maxZoomDisplayText.setText((new Integer(map.getMaxZoom())).toString());
            this.upperLeftCornerLonDisplayText.setText((new Double(map.getUpperLeftCornerLon())).toString());
            this.upperLeftCornerLatDisplayText.setText((new Double(map.getUpperLeftCornerLat())).toString());
            this.lowerLeftCornerLonDisplayText.setText((new Double(map.getLowerLeftCornerLon())).toString());
            this.lowerLeftCornerLatDisplayText.setText((new Double(map.getLowerLeftCornerLat())).toString());
            this.upperRightCornerLonDisplayText.setText((new Double(map.getUpperRightCornerLon())).toString());
            this.upperRightCornerLatDisplayText.setText((new Double(map.getUpperRightCornerLat())).toString());
            this.lowerRightCornerLonDisplayText.setText((new Double(map.getLowerRightCornerLon())).toString());
            this.lowerRightCornerLatDisplayText.setText((new Double(map.getLowerRightCornerLat())).toString());
            
            
            
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        MouseLabel = new javax.swing.JLabel();
        mouseLonDisplayText = new javax.swing.JLabel();
        mouseLonLabel = new javax.swing.JLabel();
        mouseCommaLabel = new javax.swing.JLabel();
        mouseLatDisplayText = new javax.swing.JLabel();
        mouseLatLabel = new javax.swing.JLabel();
        minZoomLabel = new javax.swing.JLabel();
        minZoomDisplayText = new javax.swing.JLabel();
        currentZoomLabel = new javax.swing.JLabel();
        currentZoomDisplayText = new javax.swing.JLabel();
        maxZoomLabel = new javax.swing.JLabel();
        maxZoomDisplayText = new javax.swing.JLabel();
        upperLeftCornerLabel = new javax.swing.JLabel();
        upperLeftCornerLonDisplayText = new javax.swing.JLabel();
        upperLeftCornerLonLabel = new javax.swing.JLabel();
        upperLeftCornerCommaLabel = new javax.swing.JLabel();
        upperLeftCornerLatDisplayText = new javax.swing.JLabel();
        upperLeftCornerLatLabel = new javax.swing.JLabel();
        lowerLeftCornerLabel = new javax.swing.JLabel();
        lowerLeftCornerLonDisplayText = new javax.swing.JLabel();
        lowerLeftCornerLonLabel = new javax.swing.JLabel();
        lowerLeftCornerCommaLabel = new javax.swing.JLabel();
        lowerLeftCornerLatDisplayText = new javax.swing.JLabel();
        lowerLeftCornerLatLabel = new javax.swing.JLabel();
        upperRightCornerLabel = new javax.swing.JLabel();
        upperRightCornerLonDisplayText = new javax.swing.JLabel();
        upperRightCornerLonLabel = new javax.swing.JLabel();
        upperRightCornerCommaLabel = new javax.swing.JLabel();
        upperRightCornerLatDisplayText = new javax.swing.JLabel();
        upperRightCornerLatLabel = new javax.swing.JLabel();
        lowerRightCornerLabel = new javax.swing.JLabel();
        lowerRightCornerLonDisplayText = new javax.swing.JLabel();
        lowerRightCornerLonLabel = new javax.swing.JLabel();
        lowerRightCornerCommaLabel = new javax.swing.JLabel();
        lowerRightCornerLatDisplayText = new javax.swing.JLabel();
        lowerRightCornerLatLabel = new javax.swing.JLabel();
        debugConsoleLabel = new javax.swing.JLabel();

        setOpaque(false);
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0};
        layout.rowHeights = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0};
        setLayout(layout);

        MouseLabel.setText("Current Mouse Position : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(MouseLabel, gridBagConstraints);

        mouseLonDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(mouseLonDisplayText, gridBagConstraints);

        mouseLonLabel.setText("Lon.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        add(mouseLonLabel, gridBagConstraints);

        mouseCommaLabel.setText(",");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        add(mouseCommaLabel, gridBagConstraints);

        mouseLatDisplayText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mouseLatDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 20;
        add(mouseLatDisplayText, gridBagConstraints);

        mouseLatLabel.setText("Lat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 2;
        add(mouseLatLabel, gridBagConstraints);

        minZoomLabel.setText("Min Zoom : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(minZoomLabel, gridBagConstraints);

        minZoomDisplayText.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        add(minZoomDisplayText, gridBagConstraints);

        currentZoomLabel.setText("Current Zoom : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(currentZoomLabel, gridBagConstraints);

        currentZoomDisplayText.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        add(currentZoomDisplayText, gridBagConstraints);

        maxZoomLabel.setText("Max Zoom : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(maxZoomLabel, gridBagConstraints);

        maxZoomDisplayText.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        add(maxZoomDisplayText, gridBagConstraints);

        upperLeftCornerLabel.setText("Upper Left Corner : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(upperLeftCornerLabel, gridBagConstraints);

        upperLeftCornerLonDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        add(upperLeftCornerLonDisplayText, gridBagConstraints);

        upperLeftCornerLonLabel.setText("Lon.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        add(upperLeftCornerLonLabel, gridBagConstraints);

        upperLeftCornerCommaLabel.setText(",");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        add(upperLeftCornerCommaLabel, gridBagConstraints);

        upperLeftCornerLatDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 10;
        add(upperLeftCornerLatDisplayText, gridBagConstraints);

        upperLeftCornerLatLabel.setText("Lat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        add(upperLeftCornerLatLabel, gridBagConstraints);

        lowerLeftCornerLabel.setText("Lower Left Corner : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lowerLeftCornerLabel, gridBagConstraints);

        lowerLeftCornerLonDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        add(lowerLeftCornerLonDisplayText, gridBagConstraints);

        lowerLeftCornerLonLabel.setText("Lon.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 12;
        add(lowerLeftCornerLonLabel, gridBagConstraints);

        lowerLeftCornerCommaLabel.setText(",");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        add(lowerLeftCornerCommaLabel, gridBagConstraints);

        lowerLeftCornerLatDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 12;
        add(lowerLeftCornerLatDisplayText, gridBagConstraints);

        lowerLeftCornerLatLabel.setText("Lat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 12;
        add(lowerLeftCornerLatLabel, gridBagConstraints);

        upperRightCornerLabel.setText("Upper Right Corner : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(upperRightCornerLabel, gridBagConstraints);

        upperRightCornerLonDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        add(upperRightCornerLonDisplayText, gridBagConstraints);

        upperRightCornerLonLabel.setText("Lon.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 14;
        add(upperRightCornerLonLabel, gridBagConstraints);

        upperRightCornerCommaLabel.setText(",");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 14;
        add(upperRightCornerCommaLabel, gridBagConstraints);

        upperRightCornerLatDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 14;
        add(upperRightCornerLatDisplayText, gridBagConstraints);

        upperRightCornerLatLabel.setText("Lat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 14;
        add(upperRightCornerLatLabel, gridBagConstraints);

        lowerRightCornerLabel.setText("Lower Right Corner : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lowerRightCornerLabel, gridBagConstraints);

        lowerRightCornerLonDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        add(lowerRightCornerLonDisplayText, gridBagConstraints);

        lowerRightCornerLonLabel.setText("Lon.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 16;
        add(lowerRightCornerLonLabel, gridBagConstraints);

        lowerRightCornerCommaLabel.setText(",");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 16;
        add(lowerRightCornerCommaLabel, gridBagConstraints);

        lowerRightCornerLatDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 8;
        gridBagConstraints.gridy = 16;
        add(lowerRightCornerLatDisplayText, gridBagConstraints);

        lowerRightCornerLatLabel.setText("Lat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 16;
        add(lowerRightCornerLatLabel, gridBagConstraints);

        debugConsoleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        debugConsoleLabel.setText("Debug Console");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 11;
        add(debugConsoleLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MouseLabel;
    private javax.swing.JLabel currentZoomDisplayText;
    private javax.swing.JLabel currentZoomLabel;
    private javax.swing.JLabel debugConsoleLabel;
    private javax.swing.JLabel lowerLeftCornerCommaLabel;
    private javax.swing.JLabel lowerLeftCornerLabel;
    private javax.swing.JLabel lowerLeftCornerLatDisplayText;
    private javax.swing.JLabel lowerLeftCornerLatLabel;
    private javax.swing.JLabel lowerLeftCornerLonDisplayText;
    private javax.swing.JLabel lowerLeftCornerLonLabel;
    private javax.swing.JLabel lowerRightCornerCommaLabel;
    private javax.swing.JLabel lowerRightCornerLabel;
    private javax.swing.JLabel lowerRightCornerLatDisplayText;
    private javax.swing.JLabel lowerRightCornerLatLabel;
    private javax.swing.JLabel lowerRightCornerLonDisplayText;
    private javax.swing.JLabel lowerRightCornerLonLabel;
    private javax.swing.JLabel maxZoomDisplayText;
    private javax.swing.JLabel maxZoomLabel;
    private javax.swing.JLabel minZoomDisplayText;
    private javax.swing.JLabel minZoomLabel;
    private javax.swing.JLabel mouseCommaLabel;
    private javax.swing.JLabel mouseLatDisplayText;
    private javax.swing.JLabel mouseLatLabel;
    private javax.swing.JLabel mouseLonDisplayText;
    private javax.swing.JLabel mouseLonLabel;
    private javax.swing.JLabel upperLeftCornerCommaLabel;
    private javax.swing.JLabel upperLeftCornerLabel;
    private javax.swing.JLabel upperLeftCornerLatDisplayText;
    private javax.swing.JLabel upperLeftCornerLatLabel;
    private javax.swing.JLabel upperLeftCornerLonDisplayText;
    private javax.swing.JLabel upperLeftCornerLonLabel;
    private javax.swing.JLabel upperRightCornerCommaLabel;
    private javax.swing.JLabel upperRightCornerLabel;
    private javax.swing.JLabel upperRightCornerLatDisplayText;
    private javax.swing.JLabel upperRightCornerLatLabel;
    private javax.swing.JLabel upperRightCornerLonDisplayText;
    private javax.swing.JLabel upperRightCornerLonLabel;
    // End of variables declaration//GEN-END:variables
}
