/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mappanel.window;


import javax.swing.*;

class DebugConsole extends javax.swing.JPanel
{

    private MapPanel map;

    /**
     * Creates new form DebugConsole
     */
    private DebugConsole()
    {
        initComponents();
    }

    public DebugConsole(MapPanel map)
    {
        this.map = map;
        initComponents();
    }

    public static void main(String[] args)
    {
        JFrame frame = new JFrame(DebugConsole.class.getSimpleName());
        frame.add(new DebugConsole());
        frame.pack();
        frame.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        frame.setResizable(true);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }

    

    public void tick()
    {
        if(this.isVisible())
        {
            this.mouseLonDisplayText.setText((new Double(map.getMouseLon())).toString());
            this.mouseLatDisplayText.setText((new Double(map.getMouseLat())).toString());
            this.minZoomDisplayText.setText((new Integer(map.getMinZoom())).toString());
            this.currentZoomDisplayText.setText((new Integer(map.getZoom())).toString());
            this.maxZoomDisplayText.setText((new Integer(map.getMaxZoom())).toString());
            this.upperLeftCornerLonDisplayText.setText((new Double(map.getUpperLeftCornerLon())).toString());
            this.upperLeftCornerLatDisplayText.setText((new Double(map.getUpperLeftCornerLat())).toString());
            this.lowerLeftCornerLonDisplayText.setText((new Double(map.getLowerLeftCornerLon())).toString());
            this.lowerLeftCornerLatDisplayText.setText((new Double(map.getLowerLeftCornerLat())).toString());
            this.upperRightCornerLonDisplayText.setText((new Double(map.getUpperRightCornerLon())).toString());
            this.lowerRightCornerLatDisplayText.setText((new Double(map.getUpperRightCornerLat())).toString());
            this.lowerRightCornerLonDisplayText.setText((new Double(map.getLowerRightCornerLon())).toString());
            this.lowerRightCornerLatDisplayText.setText((new Double(map.getLowerRightCornerLat())).toString());



        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        JLabel mouseLabel = new JLabel();
        mouseLonDisplayText = new javax.swing.JTextField();
        mouseLonLabel = new javax.swing.JLabel();
        mouseCommaLabel = new javax.swing.JLabel();
        mouseLatDisplayText = new javax.swing.JTextField();
        mouseLatLabel = new javax.swing.JLabel();
        JLabel minZoomLabel = new JLabel();
        minZoomDisplayText = new javax.swing.JTextField();
        JLabel currentZoomLabel = new JLabel();
        currentZoomDisplayText = new javax.swing.JTextField();
        JLabel maxZoomLabel = new JLabel();
        maxZoomDisplayText = new javax.swing.JTextField();
        upperLeftCornerLabel = new javax.swing.JLabel();
        upperLeftCornerLonDisplayText = new javax.swing.JTextField();
        upperLeftCornerLonLabel = new javax.swing.JLabel();
        upperLeftCornerCommaLabel = new javax.swing.JLabel();
        upperLeftCornerLatDisplayText = new javax.swing.JTextField();
        upperLeftCornerLatLabel = new javax.swing.JLabel();
        JLabel lowerLeftCornerLabel = new JLabel();
        lowerLeftCornerLonDisplayText = new javax.swing.JTextField();
        JLabel lowerLeftCornerLonLabel = new JLabel();
        JLabel lowerLeftCornerCommaLabel = new JLabel();
        lowerLeftCornerLatDisplayText = new javax.swing.JTextField();
        JLabel lowerLeftCornerLatLabel = new JLabel();
        upperRightCornerLabel = new javax.swing.JLabel();
        upperRightCornerLonDisplayText = new javax.swing.JTextField();
        upperRightCornerLonLabel = new javax.swing.JLabel();
        upperRightCornerCommaLabel = new javax.swing.JLabel();
        lowerRightCornerLatDisplayText = new javax.swing.JTextField();
        upperRightCornerLatLabel = new javax.swing.JLabel();
        JLabel lowerRightCornerLabel = new JLabel();
        lowerRightCornerLonDisplayText = new javax.swing.JTextField();
        JLabel lowerRightCornerLonLabel = new JLabel();
        JLabel lowerRightCornerCommaLabel = new JLabel();
        JTextField jTextField12 = new JTextField();
        JLabel lowerRightCornerLatLabel = new JLabel();
        JLabel debugConsoleLabel = new JLabel();
        JPanel jPanel1 = new JPanel();
        JPanel jPanel2 = new JPanel();
        JPanel jPanel3 = new JPanel();
        JPanel jPanel4 = new JPanel();
        JPanel jPanel5 = new JPanel();
        JPanel jPanel6 = new JPanel();

        setMaximumSize(new java.awt.Dimension(352, 235));
        setMinimumSize(new java.awt.Dimension(352, 235));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(352, 235));
        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0};
        layout.rowHeights = new int[] {0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0, 7, 0};
        setLayout(layout);

        mouseLabel.setText("Current Mouse Position : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(mouseLabel, gridBagConstraints);

        mouseLonDisplayText.setEditable(false);
        mouseLonDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        mouseLonDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(mouseLonDisplayText, gridBagConstraints);

        mouseLonLabel.setText("Lon.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 6;
        add(mouseLonLabel, gridBagConstraints);

        mouseCommaLabel.setText(",");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 6;
        add(mouseCommaLabel, gridBagConstraints);

        mouseLatDisplayText.setEditable(false);
        mouseLatDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        mouseLatDisplayText.setText("00.0000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 16;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(mouseLatDisplayText, gridBagConstraints);

        mouseLatLabel.setText("Lat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 6;
        add(mouseLatLabel, gridBagConstraints);

        minZoomLabel.setText("Min Zoom : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(minZoomLabel, gridBagConstraints);

        minZoomDisplayText.setEditable(false);
        minZoomDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        minZoomDisplayText.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(minZoomDisplayText, gridBagConstraints);

        currentZoomLabel.setText("Current Zoom : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(currentZoomLabel, gridBagConstraints);

        currentZoomDisplayText.setEditable(false);
        currentZoomDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        currentZoomDisplayText.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(currentZoomDisplayText, gridBagConstraints);

        maxZoomLabel.setText("Max Zoom : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(maxZoomLabel, gridBagConstraints);

        maxZoomDisplayText.setEditable(false);
        maxZoomDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        maxZoomDisplayText.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(maxZoomDisplayText, gridBagConstraints);

        upperLeftCornerLabel.setBackground(new java.awt.Color(204, 204, 204));
        upperLeftCornerLabel.setText("Upper Left Corner : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(upperLeftCornerLabel, gridBagConstraints);

        upperLeftCornerLonDisplayText.setEditable(false);
        upperLeftCornerLonDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        upperLeftCornerLonDisplayText.setText("00.00000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(upperLeftCornerLonDisplayText, gridBagConstraints);

        upperLeftCornerLonLabel.setBackground(new java.awt.Color(204, 204, 204));
        upperLeftCornerLonLabel.setText("Lon.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 34;
        gridBagConstraints.gridy = 6;
        add(upperLeftCornerLonLabel, gridBagConstraints);

        upperLeftCornerCommaLabel.setBackground(new java.awt.Color(204, 204, 204));
        upperLeftCornerCommaLabel.setText(",");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 36;
        gridBagConstraints.gridy = 6;
        add(upperLeftCornerCommaLabel, gridBagConstraints);

        upperLeftCornerLatDisplayText.setEditable(false);
        upperLeftCornerLatDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        upperLeftCornerLatDisplayText.setText("00.00000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(upperLeftCornerLatDisplayText, gridBagConstraints);

        upperLeftCornerLatLabel.setBackground(new java.awt.Color(204, 204, 204));
        upperLeftCornerLatLabel.setText("Lat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 44;
        gridBagConstraints.gridy = 6;
        add(upperLeftCornerLatLabel, gridBagConstraints);

        lowerLeftCornerLabel.setBackground(new java.awt.Color(204, 204, 204));
        lowerLeftCornerLabel.setText("Lower Left Corner : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lowerLeftCornerLabel, gridBagConstraints);

        lowerLeftCornerLonDisplayText.setEditable(false);
        lowerLeftCornerLonDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        lowerLeftCornerLonDisplayText.setText("00.00000");

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lowerLeftCornerLonDisplayText, gridBagConstraints);

        lowerLeftCornerLonLabel.setBackground(new java.awt.Color(204, 204, 204));
        lowerLeftCornerLonLabel.setText("Lon.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 34;
        gridBagConstraints.gridy = 8;
        add(lowerLeftCornerLonLabel, gridBagConstraints);

        lowerLeftCornerCommaLabel.setBackground(new java.awt.Color(204, 204, 204));
        lowerLeftCornerCommaLabel.setText(",");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 36;
        gridBagConstraints.gridy = 8;
        add(lowerLeftCornerCommaLabel, gridBagConstraints);

        lowerLeftCornerLatDisplayText.setEditable(false);
        lowerLeftCornerLatDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        lowerLeftCornerLatDisplayText.setText("00.00000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lowerLeftCornerLatDisplayText, gridBagConstraints);

        lowerLeftCornerLatLabel.setBackground(new java.awt.Color(204, 204, 204));
        lowerLeftCornerLatLabel.setText("Lat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 44;
        gridBagConstraints.gridy = 8;
        add(lowerLeftCornerLatLabel, gridBagConstraints);

        upperRightCornerLabel.setBackground(new java.awt.Color(204, 204, 204));
        upperRightCornerLabel.setText("Upper Right Corner : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(upperRightCornerLabel, gridBagConstraints);

        upperRightCornerLonDisplayText.setEditable(false);
        upperRightCornerLonDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        upperRightCornerLonDisplayText.setText("00.00000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(upperRightCornerLonDisplayText, gridBagConstraints);

        upperRightCornerLonLabel.setBackground(new java.awt.Color(204, 204, 204));
        upperRightCornerLonLabel.setText("Lon.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 34;
        gridBagConstraints.gridy = 10;
        add(upperRightCornerLonLabel, gridBagConstraints);

        upperRightCornerCommaLabel.setBackground(new java.awt.Color(204, 204, 204));
        upperRightCornerCommaLabel.setText(",");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 36;
        gridBagConstraints.gridy = 10;
        add(upperRightCornerCommaLabel, gridBagConstraints);

        lowerRightCornerLatDisplayText.setEditable(false);
        lowerRightCornerLatDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        lowerRightCornerLatDisplayText.setText("00.00000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lowerRightCornerLatDisplayText, gridBagConstraints);

        upperRightCornerLatLabel.setBackground(new java.awt.Color(204, 204, 204));
        upperRightCornerLatLabel.setText("Lat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 44;
        gridBagConstraints.gridy = 10;
        add(upperRightCornerLatLabel, gridBagConstraints);

        lowerRightCornerLabel.setBackground(new java.awt.Color(204, 204, 204));
        lowerRightCornerLabel.setText("Lower Right Corner : ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 26;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lowerRightCornerLabel, gridBagConstraints);

        lowerRightCornerLonDisplayText.setEditable(false);
        lowerRightCornerLonDisplayText.setBackground(new java.awt.Color(255, 255, 255));
        lowerRightCornerLonDisplayText.setText("00.00000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 30;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(lowerRightCornerLonDisplayText, gridBagConstraints);

        lowerRightCornerLonLabel.setBackground(new java.awt.Color(204, 204, 204));
        lowerRightCornerLonLabel.setText("Lon.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 34;
        gridBagConstraints.gridy = 12;
        add(lowerRightCornerLonLabel, gridBagConstraints);

        lowerRightCornerCommaLabel.setBackground(new java.awt.Color(204, 204, 204));
        lowerRightCornerCommaLabel.setText(",");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 36;
        gridBagConstraints.gridy = 12;
        add(lowerRightCornerCommaLabel, gridBagConstraints);

        jTextField12.setEditable(false);
        jTextField12.setBackground(new java.awt.Color(255, 255, 255));
        jTextField12.setText("00.00000");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 40;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        add(jTextField12, gridBagConstraints);

        lowerRightCornerLatLabel.setBackground(new java.awt.Color(204, 204, 204));
        lowerRightCornerLatLabel.setText("Lat.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 44;
        gridBagConstraints.gridy = 12;
        add(lowerRightCornerLatLabel, gridBagConstraints);

        debugConsoleLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        debugConsoleLabel.setText("Debug Console");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 43;
        add(debugConsoleLabel, gridBagConstraints);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel1, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 24;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel2, gridBagConstraints);

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel3, gridBagConstraints);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 46;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel4, gridBagConstraints);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel5, gridBagConstraints);

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        add(jPanel6, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private javax.swing.JTextField currentZoomDisplayText;
    private javax.swing.JTextField lowerLeftCornerLatDisplayText;
    private javax.swing.JTextField lowerLeftCornerLonDisplayText;
    private javax.swing.JTextField lowerRightCornerLatDisplayText;
    private javax.swing.JTextField lowerRightCornerLonDisplayText;
    private javax.swing.JTextField maxZoomDisplayText;
    private javax.swing.JTextField minZoomDisplayText;
    private javax.swing.JLabel mouseCommaLabel;
    private javax.swing.JTextField mouseLatDisplayText;
    private javax.swing.JLabel mouseLatLabel;
    private javax.swing.JTextField mouseLonDisplayText;
    private javax.swing.JLabel mouseLonLabel;
    private javax.swing.JLabel upperLeftCornerCommaLabel;
    private javax.swing.JLabel upperLeftCornerLabel;
    private javax.swing.JTextField upperLeftCornerLatDisplayText;
    private javax.swing.JLabel upperLeftCornerLatLabel;
    private javax.swing.JTextField upperLeftCornerLonDisplayText;
    private javax.swing.JLabel upperLeftCornerLonLabel;
    private javax.swing.JLabel upperRightCornerCommaLabel;
    private javax.swing.JLabel upperRightCornerLabel;
    private javax.swing.JLabel upperRightCornerLatLabel;
    private javax.swing.JTextField upperRightCornerLonDisplayText;
    private javax.swing.JLabel upperRightCornerLonLabel;
    // End of variables declaration//GEN-END:variables
}

